// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 33.2
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `OpenApiCommonModelMessages.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:ProtoPayloadType)
pub enum ProtoPayloadType {
    // @@protoc_insertion_point(enum_value:ProtoPayloadType.PROTO_MESSAGE)
    PROTO_MESSAGE = 5,
    // @@protoc_insertion_point(enum_value:ProtoPayloadType.ERROR_RES)
    ERROR_RES = 50,
    // @@protoc_insertion_point(enum_value:ProtoPayloadType.HEARTBEAT_EVENT)
    HEARTBEAT_EVENT = 51,
}

impl ::protobuf::Enum for ProtoPayloadType {
    const NAME: &'static str = "ProtoPayloadType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ProtoPayloadType> {
        match value {
            5 => ::std::option::Option::Some(ProtoPayloadType::PROTO_MESSAGE),
            50 => ::std::option::Option::Some(ProtoPayloadType::ERROR_RES),
            51 => ::std::option::Option::Some(ProtoPayloadType::HEARTBEAT_EVENT),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<ProtoPayloadType> {
        match str {
            "PROTO_MESSAGE" => ::std::option::Option::Some(ProtoPayloadType::PROTO_MESSAGE),
            "ERROR_RES" => ::std::option::Option::Some(ProtoPayloadType::ERROR_RES),
            "HEARTBEAT_EVENT" => ::std::option::Option::Some(ProtoPayloadType::HEARTBEAT_EVENT),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [ProtoPayloadType] = &[
        ProtoPayloadType::PROTO_MESSAGE,
        ProtoPayloadType::ERROR_RES,
        ProtoPayloadType::HEARTBEAT_EVENT,
    ];
}

impl ::protobuf::EnumFull for ProtoPayloadType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("ProtoPayloadType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            ProtoPayloadType::PROTO_MESSAGE => 0,
            ProtoPayloadType::ERROR_RES => 1,
            ProtoPayloadType::HEARTBEAT_EVENT => 2,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

// Note, `Default` is implemented although default value is not 0
impl ::std::default::Default for ProtoPayloadType {
    fn default() -> Self {
        ProtoPayloadType::PROTO_MESSAGE
    }
}

impl ProtoPayloadType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<ProtoPayloadType>("ProtoPayloadType")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:ProtoErrorCode)
pub enum ProtoErrorCode {
    // @@protoc_insertion_point(enum_value:ProtoErrorCode.UNKNOWN_ERROR)
    UNKNOWN_ERROR = 1,
    // @@protoc_insertion_point(enum_value:ProtoErrorCode.UNSUPPORTED_MESSAGE)
    UNSUPPORTED_MESSAGE = 2,
    // @@protoc_insertion_point(enum_value:ProtoErrorCode.INVALID_REQUEST)
    INVALID_REQUEST = 3,
    // @@protoc_insertion_point(enum_value:ProtoErrorCode.TIMEOUT_ERROR)
    TIMEOUT_ERROR = 5,
    // @@protoc_insertion_point(enum_value:ProtoErrorCode.ENTITY_NOT_FOUND)
    ENTITY_NOT_FOUND = 6,
    // @@protoc_insertion_point(enum_value:ProtoErrorCode.CANT_ROUTE_REQUEST)
    CANT_ROUTE_REQUEST = 7,
    // @@protoc_insertion_point(enum_value:ProtoErrorCode.FRAME_TOO_LONG)
    FRAME_TOO_LONG = 8,
    // @@protoc_insertion_point(enum_value:ProtoErrorCode.MARKET_CLOSED)
    MARKET_CLOSED = 9,
    // @@protoc_insertion_point(enum_value:ProtoErrorCode.CONCURRENT_MODIFICATION)
    CONCURRENT_MODIFICATION = 10,
    // @@protoc_insertion_point(enum_value:ProtoErrorCode.BLOCKED_PAYLOAD_TYPE)
    BLOCKED_PAYLOAD_TYPE = 11,
}

impl ::protobuf::Enum for ProtoErrorCode {
    const NAME: &'static str = "ProtoErrorCode";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ProtoErrorCode> {
        match value {
            1 => ::std::option::Option::Some(ProtoErrorCode::UNKNOWN_ERROR),
            2 => ::std::option::Option::Some(ProtoErrorCode::UNSUPPORTED_MESSAGE),
            3 => ::std::option::Option::Some(ProtoErrorCode::INVALID_REQUEST),
            5 => ::std::option::Option::Some(ProtoErrorCode::TIMEOUT_ERROR),
            6 => ::std::option::Option::Some(ProtoErrorCode::ENTITY_NOT_FOUND),
            7 => ::std::option::Option::Some(ProtoErrorCode::CANT_ROUTE_REQUEST),
            8 => ::std::option::Option::Some(ProtoErrorCode::FRAME_TOO_LONG),
            9 => ::std::option::Option::Some(ProtoErrorCode::MARKET_CLOSED),
            10 => ::std::option::Option::Some(ProtoErrorCode::CONCURRENT_MODIFICATION),
            11 => ::std::option::Option::Some(ProtoErrorCode::BLOCKED_PAYLOAD_TYPE),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<ProtoErrorCode> {
        match str {
            "UNKNOWN_ERROR" => ::std::option::Option::Some(ProtoErrorCode::UNKNOWN_ERROR),
            "UNSUPPORTED_MESSAGE" => ::std::option::Option::Some(ProtoErrorCode::UNSUPPORTED_MESSAGE),
            "INVALID_REQUEST" => ::std::option::Option::Some(ProtoErrorCode::INVALID_REQUEST),
            "TIMEOUT_ERROR" => ::std::option::Option::Some(ProtoErrorCode::TIMEOUT_ERROR),
            "ENTITY_NOT_FOUND" => ::std::option::Option::Some(ProtoErrorCode::ENTITY_NOT_FOUND),
            "CANT_ROUTE_REQUEST" => ::std::option::Option::Some(ProtoErrorCode::CANT_ROUTE_REQUEST),
            "FRAME_TOO_LONG" => ::std::option::Option::Some(ProtoErrorCode::FRAME_TOO_LONG),
            "MARKET_CLOSED" => ::std::option::Option::Some(ProtoErrorCode::MARKET_CLOSED),
            "CONCURRENT_MODIFICATION" => ::std::option::Option::Some(ProtoErrorCode::CONCURRENT_MODIFICATION),
            "BLOCKED_PAYLOAD_TYPE" => ::std::option::Option::Some(ProtoErrorCode::BLOCKED_PAYLOAD_TYPE),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [ProtoErrorCode] = &[
        ProtoErrorCode::UNKNOWN_ERROR,
        ProtoErrorCode::UNSUPPORTED_MESSAGE,
        ProtoErrorCode::INVALID_REQUEST,
        ProtoErrorCode::TIMEOUT_ERROR,
        ProtoErrorCode::ENTITY_NOT_FOUND,
        ProtoErrorCode::CANT_ROUTE_REQUEST,
        ProtoErrorCode::FRAME_TOO_LONG,
        ProtoErrorCode::MARKET_CLOSED,
        ProtoErrorCode::CONCURRENT_MODIFICATION,
        ProtoErrorCode::BLOCKED_PAYLOAD_TYPE,
    ];
}

impl ::protobuf::EnumFull for ProtoErrorCode {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("ProtoErrorCode").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            ProtoErrorCode::UNKNOWN_ERROR => 0,
            ProtoErrorCode::UNSUPPORTED_MESSAGE => 1,
            ProtoErrorCode::INVALID_REQUEST => 2,
            ProtoErrorCode::TIMEOUT_ERROR => 3,
            ProtoErrorCode::ENTITY_NOT_FOUND => 4,
            ProtoErrorCode::CANT_ROUTE_REQUEST => 5,
            ProtoErrorCode::FRAME_TOO_LONG => 6,
            ProtoErrorCode::MARKET_CLOSED => 7,
            ProtoErrorCode::CONCURRENT_MODIFICATION => 8,
            ProtoErrorCode::BLOCKED_PAYLOAD_TYPE => 9,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

// Note, `Default` is implemented although default value is not 0
impl ::std::default::Default for ProtoErrorCode {
    fn default() -> Self {
        ProtoErrorCode::UNKNOWN_ERROR
    }
}

impl ProtoErrorCode {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<ProtoErrorCode>("ProtoErrorCode")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x20OpenApiCommonModelMessages.proto*I\n\x10ProtoPayloadType\x12\x11\n\
    \rPROTO_MESSAGE\x10\x05\x12\r\n\tERROR_RES\x102\x12\x13\n\x0fHEARTBEAT_E\
    VENT\x103*\xf0\x01\n\x0eProtoErrorCode\x12\x11\n\rUNKNOWN_ERROR\x10\x01\
    \x12\x17\n\x13UNSUPPORTED_MESSAGE\x10\x02\x12\x13\n\x0fINVALID_REQUEST\
    \x10\x03\x12\x11\n\rTIMEOUT_ERROR\x10\x05\x12\x14\n\x10ENTITY_NOT_FOUND\
    \x10\x06\x12\x16\n\x12CANT_ROUTE_REQUEST\x10\x07\x12\x12\n\x0eFRAME_TOO_\
    LONG\x10\x08\x12\x11\n\rMARKET_CLOSED\x10\t\x12\x1b\n\x17CONCURRENT_MODI\
    FICATION\x10\n\x12\x18\n\x14BLOCKED_PAYLOAD_TYPE\x10\x0bBW\n(com.xtrader\
    .protocol.proto.commons.modelB\x1cContainerCommonModelMessagesP\x01\xa0\
    \x01\x01Z\x08/openapi\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(2);
            enums.push(ProtoPayloadType::generated_enum_descriptor_data());
            enums.push(ProtoErrorCode::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
