// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 33.2
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `OpenApiCommonMessages.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:ProtoMessage)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ProtoMessage {
    // message fields
    // @@protoc_insertion_point(field:ProtoMessage.payloadType)
    pub payloadType: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:ProtoMessage.payload)
    pub payload: ::std::option::Option<::std::vec::Vec<u8>>,
    // @@protoc_insertion_point(field:ProtoMessage.clientMsgId)
    pub clientMsgId: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:ProtoMessage.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ProtoMessage {
    fn default() -> &'a ProtoMessage {
        <ProtoMessage as ::protobuf::Message>::default_instance()
    }
}

impl ProtoMessage {
    pub fn new() -> ProtoMessage {
        ::std::default::Default::default()
    }

    // required uint32 payloadType = 1;

    pub fn payloadType(&self) -> u32 {
        self.payloadType.unwrap_or(0)
    }

    pub fn clear_payloadType(&mut self) {
        self.payloadType = ::std::option::Option::None;
    }

    pub fn has_payloadType(&self) -> bool {
        self.payloadType.is_some()
    }

    // Param is passed by value, moved
    pub fn set_payloadType(&mut self, v: u32) {
        self.payloadType = ::std::option::Option::Some(v);
    }

    // optional bytes payload = 2;

    pub fn payload(&self) -> &[u8] {
        match self.payload.as_ref() {
            Some(v) => v,
            None => &[],
        }
    }

    pub fn clear_payload(&mut self) {
        self.payload = ::std::option::Option::None;
    }

    pub fn has_payload(&self) -> bool {
        self.payload.is_some()
    }

    // Param is passed by value, moved
    pub fn set_payload(&mut self, v: ::std::vec::Vec<u8>) {
        self.payload = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_payload(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.payload.is_none() {
            self.payload = ::std::option::Option::Some(::std::vec::Vec::new());
        }
        self.payload.as_mut().unwrap()
    }

    // Take field
    pub fn take_payload(&mut self) -> ::std::vec::Vec<u8> {
        self.payload.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // optional string clientMsgId = 3;

    pub fn clientMsgId(&self) -> &str {
        match self.clientMsgId.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_clientMsgId(&mut self) {
        self.clientMsgId = ::std::option::Option::None;
    }

    pub fn has_clientMsgId(&self) -> bool {
        self.clientMsgId.is_some()
    }

    // Param is passed by value, moved
    pub fn set_clientMsgId(&mut self, v: ::std::string::String) {
        self.clientMsgId = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_clientMsgId(&mut self) -> &mut ::std::string::String {
        if self.clientMsgId.is_none() {
            self.clientMsgId = ::std::option::Option::Some(::std::string::String::new());
        }
        self.clientMsgId.as_mut().unwrap()
    }

    // Take field
    pub fn take_clientMsgId(&mut self) -> ::std::string::String {
        self.clientMsgId.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "payloadType",
            |m: &ProtoMessage| { &m.payloadType },
            |m: &mut ProtoMessage| { &mut m.payloadType },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "payload",
            |m: &ProtoMessage| { &m.payload },
            |m: &mut ProtoMessage| { &mut m.payload },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "clientMsgId",
            |m: &ProtoMessage| { &m.clientMsgId },
            |m: &mut ProtoMessage| { &mut m.clientMsgId },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ProtoMessage>(
            "ProtoMessage",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ProtoMessage {
    const NAME: &'static str = "ProtoMessage";

    fn is_initialized(&self) -> bool {
        if self.payloadType.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.payloadType = ::std::option::Option::Some(is.read_uint32()?);
                },
                18 => {
                    self.payload = ::std::option::Option::Some(is.read_bytes()?);
                },
                26 => {
                    self.clientMsgId = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.payloadType {
            my_size += ::protobuf::rt::uint32_size(1, v);
        }
        if let Some(v) = self.payload.as_ref() {
            my_size += ::protobuf::rt::bytes_size(2, &v);
        }
        if let Some(v) = self.clientMsgId.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.payloadType {
            os.write_uint32(1, v)?;
        }
        if let Some(v) = self.payload.as_ref() {
            os.write_bytes(2, v)?;
        }
        if let Some(v) = self.clientMsgId.as_ref() {
            os.write_string(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ProtoMessage {
        ProtoMessage::new()
    }

    fn clear(&mut self) {
        self.payloadType = ::std::option::Option::None;
        self.payload = ::std::option::Option::None;
        self.clientMsgId = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ProtoMessage {
        static instance: ProtoMessage = ProtoMessage {
            payloadType: ::std::option::Option::None,
            payload: ::std::option::Option::None,
            clientMsgId: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ProtoMessage {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ProtoMessage").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ProtoMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProtoMessage {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:ProtoErrorRes)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ProtoErrorRes {
    // message fields
    // @@protoc_insertion_point(field:ProtoErrorRes.payloadType)
    pub payloadType: ::std::option::Option<::protobuf::EnumOrUnknown<super::OpenApiCommonModelMessages::ProtoPayloadType>>,
    // @@protoc_insertion_point(field:ProtoErrorRes.errorCode)
    pub errorCode: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:ProtoErrorRes.description)
    pub description: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:ProtoErrorRes.maintenanceEndTimestamp)
    pub maintenanceEndTimestamp: ::std::option::Option<u64>,
    // special fields
    // @@protoc_insertion_point(special_field:ProtoErrorRes.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ProtoErrorRes {
    fn default() -> &'a ProtoErrorRes {
        <ProtoErrorRes as ::protobuf::Message>::default_instance()
    }
}

impl ProtoErrorRes {
    pub fn new() -> ProtoErrorRes {
        ::std::default::Default::default()
    }

    // optional .ProtoPayloadType payloadType = 1;

    pub fn payloadType(&self) -> super::OpenApiCommonModelMessages::ProtoPayloadType {
        match self.payloadType {
            Some(e) => e.enum_value_or(super::OpenApiCommonModelMessages::ProtoPayloadType::ERROR_RES),
            None => super::OpenApiCommonModelMessages::ProtoPayloadType::ERROR_RES,
        }
    }

    pub fn clear_payloadType(&mut self) {
        self.payloadType = ::std::option::Option::None;
    }

    pub fn has_payloadType(&self) -> bool {
        self.payloadType.is_some()
    }

    // Param is passed by value, moved
    pub fn set_payloadType(&mut self, v: super::OpenApiCommonModelMessages::ProtoPayloadType) {
        self.payloadType = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    // required string errorCode = 2;

    pub fn errorCode(&self) -> &str {
        match self.errorCode.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_errorCode(&mut self) {
        self.errorCode = ::std::option::Option::None;
    }

    pub fn has_errorCode(&self) -> bool {
        self.errorCode.is_some()
    }

    // Param is passed by value, moved
    pub fn set_errorCode(&mut self, v: ::std::string::String) {
        self.errorCode = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_errorCode(&mut self) -> &mut ::std::string::String {
        if self.errorCode.is_none() {
            self.errorCode = ::std::option::Option::Some(::std::string::String::new());
        }
        self.errorCode.as_mut().unwrap()
    }

    // Take field
    pub fn take_errorCode(&mut self) -> ::std::string::String {
        self.errorCode.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string description = 3;

    pub fn description(&self) -> &str {
        match self.description.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_description(&mut self) {
        self.description = ::std::option::Option::None;
    }

    pub fn has_description(&self) -> bool {
        self.description.is_some()
    }

    // Param is passed by value, moved
    pub fn set_description(&mut self, v: ::std::string::String) {
        self.description = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_description(&mut self) -> &mut ::std::string::String {
        if self.description.is_none() {
            self.description = ::std::option::Option::Some(::std::string::String::new());
        }
        self.description.as_mut().unwrap()
    }

    // Take field
    pub fn take_description(&mut self) -> ::std::string::String {
        self.description.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional uint64 maintenanceEndTimestamp = 4;

    pub fn maintenanceEndTimestamp(&self) -> u64 {
        self.maintenanceEndTimestamp.unwrap_or(0)
    }

    pub fn clear_maintenanceEndTimestamp(&mut self) {
        self.maintenanceEndTimestamp = ::std::option::Option::None;
    }

    pub fn has_maintenanceEndTimestamp(&self) -> bool {
        self.maintenanceEndTimestamp.is_some()
    }

    // Param is passed by value, moved
    pub fn set_maintenanceEndTimestamp(&mut self, v: u64) {
        self.maintenanceEndTimestamp = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "payloadType",
            |m: &ProtoErrorRes| { &m.payloadType },
            |m: &mut ProtoErrorRes| { &mut m.payloadType },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "errorCode",
            |m: &ProtoErrorRes| { &m.errorCode },
            |m: &mut ProtoErrorRes| { &mut m.errorCode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "description",
            |m: &ProtoErrorRes| { &m.description },
            |m: &mut ProtoErrorRes| { &mut m.description },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "maintenanceEndTimestamp",
            |m: &ProtoErrorRes| { &m.maintenanceEndTimestamp },
            |m: &mut ProtoErrorRes| { &mut m.maintenanceEndTimestamp },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ProtoErrorRes>(
            "ProtoErrorRes",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ProtoErrorRes {
    const NAME: &'static str = "ProtoErrorRes";

    fn is_initialized(&self) -> bool {
        if self.errorCode.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.payloadType = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                18 => {
                    self.errorCode = ::std::option::Option::Some(is.read_string()?);
                },
                26 => {
                    self.description = ::std::option::Option::Some(is.read_string()?);
                },
                32 => {
                    self.maintenanceEndTimestamp = ::std::option::Option::Some(is.read_uint64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.payloadType {
            my_size += ::protobuf::rt::int32_size(1, v.value());
        }
        if let Some(v) = self.errorCode.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(v) = self.description.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        if let Some(v) = self.maintenanceEndTimestamp {
            my_size += ::protobuf::rt::uint64_size(4, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.payloadType {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        if let Some(v) = self.errorCode.as_ref() {
            os.write_string(2, v)?;
        }
        if let Some(v) = self.description.as_ref() {
            os.write_string(3, v)?;
        }
        if let Some(v) = self.maintenanceEndTimestamp {
            os.write_uint64(4, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ProtoErrorRes {
        ProtoErrorRes::new()
    }

    fn clear(&mut self) {
        self.payloadType = ::std::option::Option::None;
        self.errorCode = ::std::option::Option::None;
        self.description = ::std::option::Option::None;
        self.maintenanceEndTimestamp = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ProtoErrorRes {
        static instance: ProtoErrorRes = ProtoErrorRes {
            payloadType: ::std::option::Option::None,
            errorCode: ::std::option::Option::None,
            description: ::std::option::Option::None,
            maintenanceEndTimestamp: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ProtoErrorRes {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ProtoErrorRes").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ProtoErrorRes {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProtoErrorRes {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:ProtoHeartbeatEvent)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ProtoHeartbeatEvent {
    // message fields
    // @@protoc_insertion_point(field:ProtoHeartbeatEvent.payloadType)
    pub payloadType: ::std::option::Option<::protobuf::EnumOrUnknown<super::OpenApiCommonModelMessages::ProtoPayloadType>>,
    // special fields
    // @@protoc_insertion_point(special_field:ProtoHeartbeatEvent.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ProtoHeartbeatEvent {
    fn default() -> &'a ProtoHeartbeatEvent {
        <ProtoHeartbeatEvent as ::protobuf::Message>::default_instance()
    }
}

impl ProtoHeartbeatEvent {
    pub fn new() -> ProtoHeartbeatEvent {
        ::std::default::Default::default()
    }

    // optional .ProtoPayloadType payloadType = 1;

    pub fn payloadType(&self) -> super::OpenApiCommonModelMessages::ProtoPayloadType {
        match self.payloadType {
            Some(e) => e.enum_value_or(super::OpenApiCommonModelMessages::ProtoPayloadType::HEARTBEAT_EVENT),
            None => super::OpenApiCommonModelMessages::ProtoPayloadType::HEARTBEAT_EVENT,
        }
    }

    pub fn clear_payloadType(&mut self) {
        self.payloadType = ::std::option::Option::None;
    }

    pub fn has_payloadType(&self) -> bool {
        self.payloadType.is_some()
    }

    // Param is passed by value, moved
    pub fn set_payloadType(&mut self, v: super::OpenApiCommonModelMessages::ProtoPayloadType) {
        self.payloadType = ::std::option::Option::Some(::protobuf::EnumOrUnknown::new(v));
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "payloadType",
            |m: &ProtoHeartbeatEvent| { &m.payloadType },
            |m: &mut ProtoHeartbeatEvent| { &mut m.payloadType },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ProtoHeartbeatEvent>(
            "ProtoHeartbeatEvent",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ProtoHeartbeatEvent {
    const NAME: &'static str = "ProtoHeartbeatEvent";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.payloadType = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.payloadType {
            my_size += ::protobuf::rt::int32_size(1, v.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.payloadType {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ProtoHeartbeatEvent {
        ProtoHeartbeatEvent::new()
    }

    fn clear(&mut self) {
        self.payloadType = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ProtoHeartbeatEvent {
        static instance: ProtoHeartbeatEvent = ProtoHeartbeatEvent {
            payloadType: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ProtoHeartbeatEvent {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ProtoHeartbeatEvent").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ProtoHeartbeatEvent {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProtoHeartbeatEvent {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1bOpenApiCommonMessages.proto\x1a\x20OpenApiCommonModelMessages.prot\
    o\"l\n\x0cProtoMessage\x12\x20\n\x0bpayloadType\x18\x01\x20\x02(\rR\x0bp\
    ayloadType\x12\x18\n\x07payload\x18\x02\x20\x01(\x0cR\x07payload\x12\x20\
    \n\x0bclientMsgId\x18\x03\x20\x01(\tR\x0bclientMsgId\"\xc9\x01\n\rProtoE\
    rrorRes\x12>\n\x0bpayloadType\x18\x01\x20\x01(\x0e2\x11.ProtoPayloadType\
    :\tERROR_RESR\x0bpayloadType\x12\x1c\n\terrorCode\x18\x02\x20\x02(\tR\te\
    rrorCode\x12\x20\n\x0bdescription\x18\x03\x20\x01(\tR\x0bdescription\x12\
    8\n\x17maintenanceEndTimestamp\x18\x04\x20\x01(\x04R\x17maintenanceEndTi\
    mestamp\"[\n\x13ProtoHeartbeatEvent\x12D\n\x0bpayloadType\x18\x01\x20\
    \x01(\x0e2\x11.ProtoPayloadType:\x0fHEARTBEAT_EVENTR\x0bpayloadTypeBL\n\
    \"com.xtrader.protocol.proto.commonsB\x17ContainerCommonMessagesP\x01\
    \xa0\x01\x01Z\x08/openapi\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::OpenApiCommonModelMessages::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(ProtoMessage::generated_message_descriptor_data());
            messages.push(ProtoErrorRes::generated_message_descriptor_data());
            messages.push(ProtoHeartbeatEvent::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
